repos:
  - repo: local

    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        pass_filenames: false
        args: [ . ]
        stages: [ commit ]

      - id: sort-all
        name: sort-all
        entry: sort-all
        language: python
        types: [ python ]
        stages: [ commit ]

      - id: black
        name: black
        entry: black
        language: python
        pass_filenames: false
        args: [ . ]
        stages: [ commit ]

      - id: flake8
        name: flake8
        entry: pflake8
        language: python
        pass_filenames: false
        stages: [ commit ]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        pass_filenames: false
        stages: [ commit ]

      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        stages: [ commit ]
