repos:
  - repo: local

    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        pass_filenames: false
        args: [ . ]
        stages: [ commit ]

      - id: black
        name: black
        entry: black
        language: system
        pass_filenames: false
        args: [ . ]
        stages: [ commit ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        pass_filenames: false
        args: [ . ]
        stages: [ commit ]

      - id: pytest
        name: pytest testing
        entry: pytest
        language: system
        pass_filenames: false
        args: [ --cov=valtypes, tests ]
        stages: [ commit ]
