repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: sort-all
        name: sort-all
        entry: poetry run sort-all
        language: system
        stages: [ commit ]

      - id: black
        name: black
        entry: poetry run black .
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: flake8
        name: flake8
        entry: poetry run pflake8 valtypes tests testing
        language: system
        pass_filenames: false
        stages: [ commit ]

      # - id: mypy
      #   name: mypy
      #   entry: poetry run mypy
      #   language: system
      #   pass_filenames: false
      #   stages: [ commit ]

      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: pyright-verify
        name: pyright-verify
        entry: poetry run pyright --verifytypes valtypes
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        stages: [ commit ]
