name: CD

on:
  release:
    types: [released]

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@main
        with:
          version: latest
          virtualenvs-create: false
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
