name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@main
        with:
          version: latest
          virtualenvs-create: false
      - run: poetry install
      - run: pflake8
      - run: mypy

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@main
        with:
          version: latest
          virtualenvs-create: false
      - run: poetry install
      - run: pytest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@main
        with:
          version: latest
          virtualenvs-create: false
      - run: poetry install
      - run: coverage run -m pytest
      - run: coverage xml
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
