name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .mypy_cache
            .pytest_cache
          key: ${{ github.ref_name }}
      - name: Run flake8
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          runCmd: poetry run pre-commit run --all-files flake8

  # mypy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Restore venv
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           .venv
  #         key: ${{ hashFiles('poetry.lock') }}
  #     - name: Restore cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           .mypy_cache
  #           .pytest_cache
  #         key: ${{ github.ref_name }}
  #     - name: Run mypy
  #       uses: devcontainers/ci@v0.2
  #       with:
  #         cacheFrom: ghcr.io/${{ github.repository }}
  #         runCmd: poetry run pre-commit run --all-files mypy

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .mypy_cache
            .pytest_cache
          key: ${{ github.ref_name }}
      - name: Run pyright
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          runCmd: poetry run pre-commit run --all-files pyright

  pyright-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .mypy_cache
            .pytest_cache
          key: ${{ github.ref_name }}
      - name: Run pyright-verify
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          runCmd: poetry run pre-commit run --all-files pyright-verify

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore venv
        uses: actions/cache@v3
        with:
          path: |
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .mypy_cache
            .pytest_cache
          key: ${{ github.ref_name }}
      - name: Run pytest
        uses: devcontainers/ci@v0.2
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          runCmd: poetry run pre-commit run --all-files pytest
