name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@main
        with:
          version: latest
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: |
          poetry run pre-commit run --all-files flake8
          poetry run pre-commit run --all-files mypy
      - name: Test
        run: poetry run pre-commit run --all-files pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          verbose: true
          fail_ci_if_error: true
