name: Create release

on:
  push:
    branches: [main]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@main
        with:
          release-type: python
          package-name: valtypes
